package:
  name: wp-theme-twentytwentyfour
  version: 1.2
  epoch: 0
  description: "Twenty Twenty-Four"
  target-architecture:
    - aarch64
    - x86_64
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: TODO
  dependencies:
    runtime:
      - wordpress

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub

pipeline:
  - uses: wporg
    with:
      slug: twentytwentyfour
      type: theme
      sha256: 6c62a003877a25869fb46231826695d76aa9d99970cc4dc3362b91ae2254f3d7